updated for mac

diff --git a/zsh/oh-my-zsh/custom/themes/powerlevel10k/gitstatus/build b/zsh/oh-my-zsh/custom/themes/powerlevel10k/gitstatus/build
--- a/zsh/oh-my-zsh/custom/themes/powerlevel10k/gitstatus/build
+++ b/zsh/oh-my-zsh/custom/themes/powerlevel10k/gitstatus/build
@@ -9,6 +9,27 @@ if [ -n "${ZSH_VERSION:-}" ]; then
   emulate sh -o err_exit -o no_unset
 fi
 
+export LC_ALL=C
+
+if [ -z "${ZSH_VERSION-}" ] && command -v zsh >/dev/null 2>&1; then
+  # Avoid bash 3.*.
+  case "${BASH_VERSION-}" in
+    [0-3].*) exec zsh "$0" "$@";;
+  esac
+fi
+
+# Avoid ksh: https://github.com/romkatv/gitstatus/issues/282.
+if [ -n "${KSH_VERSION-}" ]; then
+  if [ -z "${ZSH_VERSION-}" ] && command -v zsh >/dev/null 2>&1; then
+    exec zsh "$0" "$@"
+  elif [ -z "${BASH_VERSION-}" ] && command -v bash >/dev/null 2>&1 &&
+       bash_version="$(bash --version 2>&1)"; then
+    case "$bash_version" in
+      *version\ [4-9]*|*version\ [1-9][0-9]*) exec bash "$0" "$@";;
+    esac
+  fi
+fi
+
 usage="$(command cat <<\END
 Usage: build [-m ARCH] [-c CPU] [-d CMD] [-i IMAGE] [-s] [-w]
 
@@ -27,7 +48,7 @@ Options:
             succeed; on some operating systems this option is not
             supported; on others it can have partial effect
   -w        automatically download tarballs for dependencies if they
-            don't already exist in ./deps; dependencies are described
+            do not already exist in ./deps; dependencies are described
             in ./build.info
 END
 )"
@@ -47,12 +68,12 @@ workdir="$(command pwd)"
 
 narg() { echo $#; }
 
-if [ "$(narg $workdir)" != 1 -o -z "${workdir##*:*}" ]; then
+if [ "$(narg $workdir)" != 1 -o -z "${workdir##*:*}" -o -z "${workdir##*=*}" ]; then
   >&2 echo "[error] cannot build in this directory: $workdir"
   exit 1
 fi
 
-appname=gitstatusd-"$gitstatus_kernel"-"$gitstatus_arch"
+appname=gitstatusd
 libgit2_tmp="$outdir"/deps/"$appname".libgit2.tmp
 
 cleanup() {
@@ -68,11 +89,22 @@ trap cleanup INT QUIT TERM ILL PIPE
 if [ -n "$gitstatus_install_tools" ]; then
   case "$gitstatus_kernel" in
     linux)
-      command apk update
-      command apk add binutils cmake gcc g++ git make musl-dev perl-utils
+      if command -v apk >/dev/null 2>&1; then
+        command apk update
+        command apk add binutils cmake gcc g++ git make musl-dev perl-utils
+      elif command -v apt-get >/dev/null 2>&1; then
+        apt-get update
+        apt-get install -y binutils cmake gcc g++ make wget
+      else
+        >&2 echo "[error] -s is not supported on this system"
+        exit 1
+      fi
     ;;
-    freebsd)
-      command pkg install -y cmake gmake binutils gcc git perl5
+    freebsd|dragonfly)
+      command pkg install -y cmake gmake binutils git perl5 wget
+    ;;
+    openbsd)
+      command pkg_add cmake gmake gcc g++ git wget
     ;;
     netbsd)
       command pkgin -y install cmake gmake binutils git
@@ -82,17 +114,20 @@ if [ -n "$gitstatus_install_tools" ]; then
         >&2 echo "[error] please run 'xcode-select --install' and retry"
         exit 1
       fi
-      if ! command -v brew >/dev/null 2>&1; then
-        >&2 echo "[error] please install homebrew from https://brew.sh/ and retry"
+      if command -v port >/dev/null 2>&1; then
+        sudo port -N install libiconv cmake wget
+      elif command -v brew >/dev/null 2>&1; then
+        for formula in libiconv cmake git wget; do
+          if command brew ls --version "$formula" &>/dev/null; then
+            command brew upgrade "$formula"
+          else
+            command brew install "$formula"
+          fi
+        done
+      else
+        >&2 echo "[error] please install MacPorts or Homebrew and retry"
         exit 1
       fi
-      for formula in libiconv cmake git wget; do
-        if command brew list "$formula" &>/dev/null; then
-          command brew upgrade "$formula"
-        else
-          command brew install "$formula"
-        fi
-      done
     ;;
     msys*|mingw*)
       command pacman -Syu --noconfirm
@@ -106,65 +141,138 @@ if [ -n "$gitstatus_install_tools" ]; then
 fi
 
 cpus="$(command getconf _NPROCESSORS_ONLN 2>/dev/null)" ||
-  cpus="$(command sysctl -n hw.ncpu 2>/dev/null)" ||
+  cpus="$(command sysctl -n hw.ncpu 2>/dev/null)"       ||
   cpus=8
 
 case "$gitstatus_cpu" in
-  ppc64le) archflag="-mcpu";;
-  *)       archflag="-march";;
+  powerpc64|powerpc64le)
+    archflag="-mcpu"
+  ;;
+  *)
+    archflag="-march"
+  ;;
 esac
 
-cflags="$archflag=$gitstatus_cpu -fno-plt"
+cflags="$archflag=$gitstatus_cpu -fno-plt -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fpie"
+ldflags=
+static_pie=
+
+if [ -z "${CC-}" ]; then
+  case "$gitstatus_kernel" in
+    freebsd) export CC=clang;;
+    *)       export CC=cc;;
+  esac
+fi
+
+printf 'int main() {}\n' >"$workdir"/cc-test.c
+if 2>/dev/null "$CC"   \
+     -ffile-prefix-map=x=y   \
+     -Werror                 \
+     -c "$workdir"/cc-test.c \
+     -o "$workdir"/cc-test.o; then
+  cflags="$cflags -ffile-prefix-map=$workdir/="
+fi
+
+command rm -f -- "$workdir"/cc-test "$workdir"/cc-test.o
+if 2>/dev/null "$CC"          \
+     -fstack-clash-protection \
+     -Werror                  \
+     -c "$workdir"/cc-test.c  \
+     -o "$workdir"/cc-test.o; then
+  cflags="$cflags -fstack-clash-protection"
+fi
+
+command rm -f -- "$workdir"/cc-test "$workdir"/cc-test.o
+if 2>/dev/null "$CC"         \
+     -fcf-protection         \
+     -Werror                 \
+     -c "$workdir"/cc-test.c \
+     -o "$workdir"/cc-test.o; then
+  cflags="$cflags -fcf-protection"
+fi
+
+command rm -f -- "$workdir"/cc-test "$workdir"/cc-test.o
+if 2>/dev/null "$CC"                             \
+     -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now \
+     -Werror                                           \
+     "$workdir"/cc-test.c                              \
+     -o "$workdir"/cc-test; then
+  ldflags="$ldflags -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
+fi
+
+command rm -f -- "$workdir"/cc-test "$workdir"/cc-test.o
+if 2>/dev/null "$CC" \
+     -fpie -static-pie     \
+     -Werror               \
+     "$workdir"/cc-test.c  \
+     -o "$workdir"/cc-test; then
+  static_pie='-static-pie'
+fi
 
 if [ "$gitstatus_cpu" = x86-64 ]; then
   cflags="$cflags -mtune=generic"
 fi
 
 libgit2_cmake_flags=
-libgit2_cflags="$cflags"
+libgit2_cflags="${CFLAGS-} $cflags -O3 -DNDEBUG"
 
 gitstatus_cxx=g++
-gitstatus_cxxflags="$cflags -I${workdir}/libgit2/include -DGITSTATUS_ZERO_NSEC -D_GNU_SOURCE"
-gitstatus_ldflags="-L${workdir}/libgit2/build"
+gitstatus_cxxflags="${CXXFLAGS-} $cflags -I${workdir}/libgit2/include -DGITSTATUS_ZERO_NSEC -D_GNU_SOURCE -D_GLIBCXX_ASSERTIONS"
+gitstatus_ldflags="${LDFLAGS-} $ldflags -L${workdir}/libgit2/build"
 gitstatus_ldlibs=
 gitstatus_make=make
 
 case "$gitstatus_kernel" in
   linux)
-    if [ -n "$docker_cmd" ]; then
-      gitstatus_ldflags="$gitstatus_ldflags -static"
-    fi
-    gitstatus_ldflags="$gitstatus_ldflags -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
+    gitstatus_ldflags="$gitstatus_ldflags ${static_pie:--static}"
     libgit2_cmake_flags="$libgit2_cmake_flags -DENABLE_REPRODUCIBLE_BUILDS=ON"
   ;;
   freebsd)
+    gitstatus_cxx=clang++
     gitstatus_make=gmake
-    gitstatus_ldflags="$gitstatus_ldflags -static"
-    gitstatus_ldflags="$gitstatus_ldflags -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
+    gitstatus_ldflags="$gitstatus_ldflags ${static_pie:--static}"
+    libgit2_cmake_flags="$libgit2_cmake_flags -DENABLE_REPRODUCIBLE_BUILDS=ON"
+  ;;
+  dragonfly)
+    gitstatus_cxx=clang++12
+    gitstatus_make=gmake
+    gitstatus_ldflags="$gitstatus_ldflags ${static_pie:--static}"
+    libgit2_cmake_flags="$libgit2_cmake_flags -DENABLE_REPRODUCIBLE_BUILDS=ON"
+  ;;
+  openbsd)
+    gitstatus_cxx=eg++
+    gitstatus_make=gmake
+    gitstatus_ldflags="$gitstatus_ldflags ${static_pie:--static}"
     libgit2_cmake_flags="$libgit2_cmake_flags -DENABLE_REPRODUCIBLE_BUILDS=ON"
   ;;
   netbsd)
     gitstatus_make=gmake
-    gitstatus_ldflags="$gitstatus_ldflags -static"
-    gitstatus_ldflags="$gitstatus_ldflags -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
+    gitstatus_ldflags="$gitstatus_ldflags ${static_pie:--static}"
     libgit2_cmake_flags="$libgit2_cmake_flags -DENABLE_REPRODUCIBLE_BUILDS=ON"
   ;;
   darwin)
     command mkdir -- "$workdir"/lib
-    command ln -s -- /usr/local/opt/libiconv/lib/libiconv.a "$workdir"/lib
+    if [ -e /opt/local/lib/libiconv.a ]; then
+      command ln -s -- /opt/local/lib/libiconv.a "$workdir"/lib
+      libgit2_cflags="$libgit2_cflags -I/opt/local/include"
+      gitstatus_cxxflags="$gitstatus_cxxflags -I/opt/local/include"
+    else
+      brew_prefix="$(command brew --prefix)"
+      command ln -s -- "$brew_prefix"/opt/libiconv/lib/libiconv.a "$workdir"/lib
+      libgit2_cflags="$libgit2_cflags -I"$brew_prefix"/opt/libiconv/include"
+      gitstatus_cxxflags="$gitstatus_cxxflags -I"$brew_prefix"/opt/libiconv/include"
+    fi
     libgit2_cmake_flags="$libgit2_cmake_flags -DUSE_ICONV=ON"
-    libgit2_cflags="$libgit2_cflags -I/usr/local/opt/libiconv/include"
-    gitstatus_cxxflags="$gitstatus_cxxflags -I/usr/local/opt/libiconv/include"
     gitstatus_ldlibs="$gitstatus_ldlibs -liconv"
     gitstatus_ldflags="$gitstatus_ldflags -L${workdir}/lib"
     libgit2_cmake_flags="$libgit2_cmake_flags -DENABLE_REPRODUCIBLE_BUILDS=OFF"
   ;;
   msys*|mingw*)
-    gitstatus_ldflags="$gitstatus_ldflags -static"
+    gitstatus_ldflags="$gitstatus_ldflags ${static_pie:--static}"
     libgit2_cmake_flags="$libgit2_cmake_flags -DENABLE_REPRODUCIBLE_BUILDS=ON"
   ;;
   cygwin*)
-    gitstatus_ldflags="$gitstatus_ldflags -static"
+    gitstatus_ldflags="$gitstatus_ldflags ${static_pie:--static}"
     libgit2_cmake_flags="$libgit2_cmake_flags -DENABLE_REPRODUCIBLE_BUILDS=ON"
   ;;
   *)
@@ -173,7 +281,7 @@ case "$gitstatus_kernel" in
   ;;
 esac
 
-for cmd in cat cmake gcc g++ git ld ln mkdir rm strip tar "$gitstatus_make"; do
+for cmd in cat cmake git ld ln mkdir rm strip tar "$gitstatus_make"; do
   if ! command -v "$cmd" >/dev/null 2>&1; then
     if [ -n "$gitstatus_install_tools" ]; then
       >&2 echo "[internal error] $cmd not found"
@@ -207,7 +315,18 @@ if [ ! -e "$libgit2_tarball" ]; then
       fi
     fi
     libgit2_url=https://github.com/romkatv/libgit2/archive/"$libgit2_version".tar.gz
-    command wget -O "$libgit2_tmp" -- "$libgit2_url"
+    if ! >"$libgit2_tmp" command wget --no-config -qO- -- "$libgit2_url" &&
+       ! >"$libgit2_tmp" command wget             -qO- -- "$libgit2_url"; then
+      set -x
+      >&2 command which wget
+      >&2 command ls -lAd -- "$(command which wget)"
+      >&2 command ls -lAd -- "$outdir"
+      >&2 command ls -lA -- "$outdir"
+      >&2 command ls -lAd -- "$outdir"/deps
+      >&2 command ls -lA -- "$outdir"/deps
+      set +x
+      exit 1
+    fi
     command mv -f -- "$libgit2_tmp" "$libgit2_tarball"
   else
     >&2 echo "[error] file not found: deps/libgit2-"$libgit2_version".tar.gz"
@@ -253,7 +372,7 @@ command mkdir libgit2/build
 cd libgit2/build
 
 CFLAGS="$libgit2_cflags" command cmake \
-  -DCMAKE_BUILD_TYPE=Release           \
+  -DCMAKE_BUILD_TYPE=None              \
   -DZERO_NSEC=ON                       \
   -DTHREADSAFE=ON                      \
   -DUSE_BUNDLED_ZLIB=ON                \
@@ -271,7 +390,7 @@ command make -j "$cpus" VERBOSE=1
 
 APPNAME="$appname".tmp           \
   OBJDIR="$workdir"/gitstatus    \
-  CXX="$gitstatus_cxx"           \
+  CXX="${CXX:-$gitstatus_cxx}"   \
   CXXFLAGS="$gitstatus_cxxflags" \
   LDFLAGS="$gitstatus_ldflags"   \
   LDLIBS="$gitstatus_ldlibs"     \
@@ -282,16 +401,33 @@ app="$outdir"/usrbin/"$appname"
 command strip "$app".tmp
 
 command mkdir -- "$workdir"/repo
-command git -C "$workdir"/repo init
-command git -C "$workdir"/repo config user.name "Your Name"
-command git -C "$workdir"/repo config user.email "you@example.com"
-command git -C "$workdir"/repo commit --allow-empty --allow-empty-message --no-gpg-sign -m ''
+printf '[init]\n  defaultBranch = master\n' >"$workdir"/.gitconfig
+(
+  cd -- "$workdir"/repo
+  GIT_CONFIG_NOSYSTEM=1 HOME="$workdir" command git init
+  GIT_CONFIG_NOSYSTEM=1 HOME="$workdir" command git config user.name "Your Name"
+  GIT_CONFIG_NOSYSTEM=1 HOME="$workdir" command git config user.email "you@example.com"
+  GIT_CONFIG_NOSYSTEM=1 HOME="$workdir" command git commit \
+    --allow-empty --allow-empty-message --no-gpg-sign -m ''
+)
 
 resp="$(printf "hello\037$workdir/repo\036" | "$app".tmp)"
-[ -n "$resp" -a -z "${resp##hello*1*$workdir/repo*master*}" ]
+case "$resp" in
+  hello*1*/repo*master*);;
+  *)
+    >&2 echo 'error: invalid gitstatusd response for a git repo'
+    exit 1
+  ;;
+esac
 
 resp="$(printf 'hello\037\036' | "$app".tmp)"
-[ -n "$resp" -a -z "${resp##hello*0*}" ]
+case "$resp" in
+  hello*0*);;
+  *)
+    >&2 echo 'error: invalid gitstatusd response for a non-repo'
+    exit 1
+  ;;
+esac
 
 command mv -f -- "$app".tmp "$app"
 
@@ -399,12 +535,16 @@ fi
 
 if [ -z "$gitstatus_cpu" ]; then
   case "$gitstatus_arch" in
-    armv6l)         gitstatus_cpu=armv6;;
+    armel)          gitstatus_cpu=armv5;;
+    armv6l|armhf)   gitstatus_cpu=armv6;;
     armv7l)         gitstatus_cpu=armv7;;
-    aarch64)        gitstatus_cpu=armv8-a;;
-    ppc64le)        gitstatus_cpu=powerpc64le;;
+    arm64|aarch64)  gitstatus_cpu=armv8-a;;
+    ppc64|ppc64le)  gitstatus_cpu=powerpc64le;;
     riscv64)        gitstatus_cpu=rv64imafdc;;
+    loongarch64)    gitstatus_cpu=loongarch64;;
     x86_64|amd64)   gitstatus_cpu=x86-64;;
+    x86)            gitstatus_cpu=i586;;
+    s390x)          gitstatus_cpu=z900;;
     i386|i586|i686) gitstatus_cpu="$gitstatus_arch";;
     *)
       >&2 echo '[error] unable to infer target CPU architecture'
@@ -433,12 +573,13 @@ case "$gitstatus_kernel" in
       fi
       if [ -z "$docker_image" ]; then
         case "$gitstatus_arch" in
-          x86_64)         docker_image=alpine:3.11.6;;
-          i386|i586|i686) docker_image=i386/alpine:3.11.6;;
-          armv6l)         docker_image=arm32v6/alpine:3.11.6;;
-          armv7l)         docker_image=arm32v7/alpine:3.11.6;;
-          aarch64)        docker_image=arm64v8/alpine:3.11.6;;
-          ppc64le)        docker_image=ppc64le/alpine:3.11.6;;
+          x86_64)             docker_image=alpine:3.11.6;;
+          x86|i386|i586|i686) docker_image=i386/alpine:3.11.6;;
+          armv6l|armhf)       docker_image=arm32v6/alpine:3.11.6;;
+          armv7l)             docker_image=arm32v7/alpine:3.11.6;;
+          aarch64)            docker_image=arm64v8/alpine:3.11.6;;
+          ppc64|ppc64le)      docker_image=ppc64le/alpine:3.11.6;;
+          s390x)              docker_image=s390x/alpine:3.11.6;;
           *)
             >&2 echo '[error] unable to infer docker image'
             >&2 echo 'Please specify explicitly with `-i IMAGE`.'
@@ -446,12 +587,9 @@ case "$gitstatus_kernel" in
           ;;
         esac
       fi
-    elif [ -n "$gitstatus_install_tools" ]; then
-      >&2 echo '[error] -s without -d is not supported on linux'
-      exit 1
     fi
   ;;
-  freebsd|netbsd|darwin)
+  freebsd|openbsd|netbsd|darwin|dragonfly)
     if [ -n "$docker_cmd" ]; then
       >&2 echo "[error] docker (-d) is not supported on $gitstatus_kernel"
       exit 1
diff --git a/zsh/oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install b/zsh/oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install
--- a/zsh/oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install
+++ b/zsh/oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install
@@ -2,6 +2,12 @@
 #
 # This script does not have a stable API.
 
+_gitstatus_install_daemon_found() {
+  local installed="$1"
+  shift
+  [ $# = 0 ] || "$@" "$daemon" "$version" "$installed"
+}
+
 _gitstatus_install_main() {
   if [ -n "${ZSH_VERSION:-}" ]; then
     emulate -L sh -o no_unset
@@ -12,14 +18,14 @@ _gitstatus_install_main() {
   local argv1="$1"
   shift
 
-  local no_check= no_install= uname_s= uname_m= gitstatus_dir= dl_status=
+  local no_check= no_install= uname_s= uname_m= gitstatus_dir= dl_status= e=
   local opt= OPTARG= OPTIND=1
 
-  while getopts ':s:m:d:p:fnh' opt "$@"; do
+  while getopts ':s:m:d:p:e:fnh' opt "$@"; do
     case "$opt" in
       h)
         command cat <<\END
-Usage: install [-s KERNEL] [-m ARCH] [-d DIR] [-p CMD] [-f|-n] [-- CMD [ARG]...]
+Usage: install [-s KERNEL] [-m ARCH] [-d DIR] [-p CMD] [-e ERRFD] [-f|-n] [-- CMD [ARG]...]
 
 If positional arguments are specified, call this on success:
 
@@ -36,6 +42,7 @@ Options:
   -m ARCH    use this instead of lowercase `uname -m`
   -d DIR     use this instead of `dirname "$0"`
   -p CMD     eval this every second while downloading gitstatusd
+  -e ERRFD   write error messages to this file descriptor
   -f         download gitstatusd even if there is one locally
   -n         do not download gitstatusd (fail instead)
 END
@@ -77,6 +84,17 @@ END
         fi
         dl_status="$OPTARG"
       ;;
+      e)
+        if [ -n "$e" ]; then
+          >&2 echo "[gitstatus] error: duplicate option: -$opt"
+          return 1
+        fi
+        if [ -z "$OPTARG" ]; then
+          >&2 echo "[error] incorrect value of -$opt: $OPTARG"
+          return 1
+        fi
+        e="$OPTARG"
+      ;;
       m)
         if [ -n "$uname_m" ]; then
           >&2 echo "[gitstatus] error: duplicate option: -$opt"
@@ -107,6 +125,7 @@ END
 
   shift "$((OPTIND - 1))"
 
+  : "${e:=2}"
   : "${gitstatus_dir:=$argv1}"
 
   if [ -n "$no_check" -a -n "$no_install" ]; then
@@ -131,14 +150,8 @@ END
       >&2 echo "[gitstatus] error: GITSTATUS_DAEMON is not absolute path: $daemon"
       return 1
     fi
-    if [ -z "$daemon" ]; then
+    if [ -z "$daemon" -a -e "$gitstatus_dir"/usrbin/gitstatusd ]; then
       daemon="$gitstatus_dir"/usrbin/gitstatusd
-      if [ ! -e "$daemon" ]; then
-        daemon="$daemon"-"$uname_s"-"$uname_m"
-        if [ ! -e "$daemon" ]; then
-          daemon=
-        fi
-      fi
     fi
     if [ -n "$daemon" ]; then
       local gitstatus_version= libgit2_version=
@@ -150,7 +163,8 @@ END
         >&2 echo "[gitstatus] internal error: empty gitstatus_version in build.info"
         return 1
       fi
-      [ $# = 0 ] || "$@" "$daemon" "$gitstatus_version" 0
+      local version="$gitstatus_version"
+      _gitstatus_install_daemon_found 0 "$@"
       return
     fi
   fi
@@ -184,23 +198,13 @@ END
 
     if [ -z "$no_check" ]; then
       # Check if a suitable gitstatusd already exists.
-      local daemon="$cache_dir"/"$file"
-      if [ -e "$daemon" ]; then
-        [ $# = 0 ] || "$@" "$daemon" "$version" 0
-        return
+      local daemon="$gitstatus_dir"/usrbin/"$file"
+      if [ ! -e "$daemon" ]; then
+        daemon="$cache_dir"/"$file"
+        [ -e "$daemon" ] || daemon=
       fi
-      daemon="$daemon"-"$uname_s"-"$uname_m"
-      if [ -e "$daemon" ]; then
-        local gitstatus_version= libgit2_version=
-        if ! . "$gitstatus_dir"/build.info; then
-          >&2 echo "[gitstatus] internal error: failed to source build.info"
-          return 1
-        fi
-        if [ -z "$gitstatus_version" ]; then
-          >&2 echo "[gitstatus] internal error: empty gitstatus_version in build.info"
-          return 1
-        fi
-        [ $# = 0 ] || "$@" "$daemon" "$gitstatus_version" 0
+      if [ -n "$daemon" ]; then
+        _gitstatus_install_daemon_found 0 "$@"
         return
       fi
     fi
@@ -218,17 +222,62 @@ END
       >&2 echo "[gitstatus] error: GITSTATUS_CACHE_DIR is not absolute: $cache_dir"
       return 1
     fi
-    [ -d "$cache_dir" ] || mkdir -p -- "$cache_dir" || return
+    if [ ! -d "$cache_dir" ] && ! mkdir -p -- "$cache_dir" || [ ! -w "$cache_dir" ]; then
+      local dir="$cache_dir"
+      while true; do
+        if [ -e "$dir" ]; then
+          if [ ! -d "$dir" ]; then
+            >&"$e" printf 'Not a directory: \033[4;31m%s\033[0m\n' "$dir"
+            >&"$e" printf '\n'
+            >&"$e" printf 'Delete it, then restart your shell.\n'
+          elif [ ! -w "$dir" ]; then
+            >&"$e" printf 'Directory is not writable: \033[4;31m%s\033[0m\n' "$dir"
+            >&"$e" printf '\n'
+            >&"$e" printf 'Make it writable, then restart your shell.\n'
+          fi
+          break
+        fi
+        if [ "$dir" = / ] || [ "$dir" = . ]; then
+          break
+        fi
+        dir="$(dirname -- "$dir")"
+      done
+      return 1
+    fi
 
-    local tmpdir
+    if [ -n "${TMPDIR-}" -a '(' '(' -d "${TMPDIR-}" -a -w "${TMPDIR-}" ')' -o '!' '(' -d /tmp -a -w /tmp ')' ')' ]; then
+      local tmp="$TMPDIR"
+    else
+      local tmp=/tmp
+    fi
     if ! command -v mktemp >/dev/null 2>&1 ||
-        ! tmpdir="$(command mktemp -d "${TMPDIR:-/tmp}"/gitstatus-install.XXXXXXXXXX)"; then
-      tmpdir="${TMPDIR:-/tmp}/gitstatus-install.tmp.$$"
-      mkdir -p -- "$tmpdir" || return
+       ! tmpdir="$(command mktemp -d "$tmp"/gitstatus-install.XXXXXXXXXX)"; then
+      tmpdir="$tmp/gitstatus-install.tmp.$$"
+      if ! mkdir -p -- "$tmpdir"; then
+        if [ "$tmp" = /tmp ]; then
+          local label='directory'
+        else
+          local label='directory (\033[1mTMPDIR\033[m)'
+        fi
+        if [ ! -e "$tmp" ]; then
+          >&"$e" printf 'Temporary '"$label"' does not exist: \033[4;31m%s\033[0m\n' "$tmp"
+          >&"$e" printf '\n'
+          >&"$e" printf 'Create it, then restart your shell.\n'
+        elif [ ! -d "$tmp" ]; then
+          >&"$e" printf 'Not a '"$label"': \033[4;31m%s\033[0m\n' "$tmp"
+          >&"$e" printf '\n'
+          >&"$e" printf 'Make it a directory, then restart your shell.\n'
+        elif [ ! -w "$tmp" ]; then
+          >&"$e" printf 'Temporary '"$label"' is not writable: \033[4;31m%s\033[0m\n' "$tmp"
+          >&"$e" printf '\n'
+          >&"$e" printf 'Make it writable, then restart your shell.\n'
+        fi
+        return 1
+      fi
     fi
 
     if ! command -v curl >/dev/null 2>&1 && ! command -v wget >/dev/null 2>&1; then
-      >&2 echo "[gitstatus] error: please install curl or wget"
+      >&"$e" printf 'Please install \033[32mcurl\033[0m or \033[32mwget\033[0m, then restart your shell.\n'
       return 1
     fi
 
@@ -258,27 +307,29 @@ END
         local data_file="$tmpdir"/"$1".tar.gz
         local hash_file="$tmpdir"/"$1".tar.gz.sha256
         local hash=
-        if command -v shasum >/dev/null 2>/dev/null; then
-          if run_cmd shasum -b -a 256 -- "$data_file" >"$hash_file"; then
-            IFS= read -r hash <"$hash_file" || hash=
-            hash="${hash%% *}"
-          fi
-        elif command -v sha256sum >/dev/null 2>/dev/null; then
-          if run_cmd sha256sum -b -- "$data_file" >"$hash_file"; then
-            IFS= read -r hash <"$hash_file" || hash=
-            hash="${hash%% *}"
-          fi
-        elif command -v sha256 >/dev/null 2>/dev/null; then
-          if run_cmd sha256 -- "$data_file" </dev/null >"$hash_file"; then
-            IFS= read -r hash <"$hash_file" || hash=
-            # Ignore sha256 output if it's from hashalot. It's incompatible.
-            if [ ${#hash} -lt 64 ]; then
-              hash=
-            else
-              hash="${hash##* }"
-            fi
-          fi
-        fi
+        {
+          command -v shasum >/dev/null 2>/dev/null                            &&
+            run_cmd shasum -b -a 256 -- "$data_file" >"$hash_file" </dev/null &&
+            IFS= read -r hash <"$hash_file"                                   &&
+            hash="${hash%% *}"                                                &&
+            [ ${#hash} -eq 64 ]
+        } || {
+          command -v sha256sum >/dev/null 2>/dev/null                         &&
+            run_cmd sha256sum -b -- "$data_file" >"$hash_file" </dev/null     &&
+            IFS= read -r hash <"$hash_file"                                   &&
+            hash="${hash%% *}"                                                &&
+            [ ${#hash} -eq 64 ]
+        } || {
+          # Note: sha256 can be from hashalot. It's incompatible.
+          # Thankfully, it produces shorter output.
+          command -v sha256 >/dev/null 2>/dev/null &&
+            run_cmd sha256 -- "$data_file" >"$hash_file" </dev/null &&
+            IFS= read -r hash <"$hash_file" &&
+            hash="${hash##* }" &&
+            [ ${#hash} -eq 64 ]
+        } || {
+          hash=
+        }
         [ "$1" = 1 -a -z "$hash" -o "$hash" = "$sha256" ]
       }
 
@@ -294,7 +345,7 @@ END
           fi
         fi
         local cmd part url ret
-        for cmd in 'curl -q -fsSL' 'wget --no-config -qO-' 'wget -qO-' 'curl -fsSL'; do
+        for cmd in 'curl -kfsSL' 'wget -qO-' 'curl -q -kfsSL' 'wget --no-config -qO-'; do
           part=0
           while true; do
             if [ "$part" = 2 ]; then
@@ -322,9 +373,9 @@ END
 
       local trapped=
       trap 'trapped=1' $sig
-      fetch 1 "$url1" & 
+      fetch 1 "$url1" &
       local pid1="$!"
-      fetch 2 "$url2" & 
+      fetch 2 "$url2" &
       local pid2="$!"
 
       local die="trap - $sig; kill -- $pid1 $pid2 2>/dev/null; wait -- $pid1 $pid2 2>/dev/null; exit 1"
@@ -379,10 +430,12 @@ END
       trap - $sig
 
       if [ -z "$n" ]; then
-        >&2 echo "[gitstatus] error: failed to download gitstatusd from any mirror"
-        >&2 echo ""
-        >&2 echo "  1. $url1"
-        >&2 echo "  2. $url2"
+        >&"$e" printf 'Failed to download \033[32m%s\033[0m from any mirror:\n' "$file"
+        >&"$e" printf '\n'
+        >&"$e" printf '  1. \033[4m%s\033[0m\n' "$url1"
+        >&"$e" printf '  2. \033[4m%s\033[0m\n' "$url2"
+        >&"$e" printf '\n'
+        >&"$e" printf 'Check your internet connection, then restart your shell.\n'
         exit 1
       fi
 
@@ -394,7 +447,7 @@ END
         tmpfile="$cache_dir"/gitstatusd.tmp.$$
       fi
 
-      command mv -f -- "$tmpdir"/gitstatusd-* "$tmpfile" || exit
+      command mv -f -- "$tmpdir"/"$file" "$tmpfile" || exit
       command mv -f -- "$tmpfile" "$cache_dir"/"$file" && exit
       command rm -f -- "$cache_dir"/"$file"
       command mv -f -- "$tmpfile" "$cache_dir"/"$file" && exit
@@ -406,13 +459,13 @@ END
     command rm -rf -- "$tmpdir"
     [ "$ret" = 0 ] || return
 
-    [ $# = 0 ] || "$@" "$daemon" "$version" 1
+    _gitstatus_install_daemon_found 1 "$@"
     return
   done <"$gitstatus_dir"/install.info
 
-  >&2 echo "[gitstatus] error: no gitstatusd found for $uname_s $uname_m"
-  >&2 echo ""
-  >&2 echo "See: https://github.com/romkatv/gitstatus/blob/master/README.md#compiling"
+  >&"$e" printf 'There is no prebuilt \033[32mgitstatusd\033[0m for \033[1m%s\033[0m.\n' "$uname_s $uname_m"
+  >&"$e" printf '\n'
+  >&"$e" printf 'See: \033[4mhttps://github.com/romkatv/gitstatus#compiling\033[0m\n'
   return 1
 }
 
